[package]
name = "xtask"
version = "0.1.0"
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true

[lib]
path = "src/lib.rs"

[[bin]]
name = "xtask"
path = "src/main.rs"

[dependencies]
minicontainer-bundle = { path = "../crates/bundle" }
minicontainer-protocol = { path = "../crates/protocol" }
minios-abi.workspace = true
libc = "0.2"
sha2 = "0.10"
