[package]
name = "minictr"
version = "1.0.0"
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true

[[bin]]
name = "minictr"
path = "src/main.rs"

[dependencies]
libc = "0.2"
minicontainer-bundle = { path = "../bundle" }
minicontainer-oci = { path = "../oci" }
minicontainer-runtime = { path = "../runtime" }
