//! Writes one canonical OCI Image Layout directory from MiniBundle bytes.
//!
//! The layout holds the whole bundle as a single opaque layer blob. The
//! destination must not exist: files land in a sibling temporary directory
//! first, then one rename publishes them, and the finished layout is read
//! back before reporting success.

use crate::{
    OciError,
    json::{render_config, render_index, render_manifest, render_oci_layout},
};
use minicontainer_bundle::format_digest;
use sha2::{Digest, Sha256};
use std::{
    fs,
    path::{Path, PathBuf},
    sync::atomic::{AtomicU64, Ordering},
};

/// Digests of a written layout, from the layer up to the index.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub struct ExportedLayout {
    /// SHA-256 of the MiniBundle layer blob.
    pub layer: [u8; 32],
    /// SHA-256 of the config blob.
    pub config: [u8; 32],
    /// SHA-256 of the manifest blob.
    pub manifest: [u8; 32],
    /// SHA-256 of `index.json`.
    pub index: [u8; 32],
}

/// Exports validated MiniBundle bytes as an OCI Image Layout directory.
pub fn export_bundle(bundle: &[u8], dest: &Path) -> Result<ExportedLayout, OciError> {
    let parsed = minicontainer_bundle::parse(bundle).map_err(OciError::Bundle)?;
    let args: Vec<&str> = parsed.manifest.args().collect();
    let layer = digest_of(bundle);
    let config = render_config(parsed.manifest.name(), &args, &format_digest(layer));
    let config_digest = digest_of(config.as_bytes());
    let manifest = render_manifest(
        &format_digest(config_digest),
        config.len() as u64,
        &format_digest(layer),
        bundle.len() as u64,
    );
    let manifest_digest = digest_of(manifest.as_bytes());
    let index = render_index(&format_digest(manifest_digest), manifest.len() as u64);
    let exported = ExportedLayout {
        layer,
        config: config_digest,
        manifest: manifest_digest,
        index: digest_of(index.as_bytes()),
    };

    if fs::symlink_metadata(dest).is_ok() {
        return Err(OciError::DestinationExists {
            path: dest.to_owned(),
        });
    }
    if let Some(parent) = dest.parent()
        && !parent.as_os_str().is_empty()
    {
        fs::create_dir_all(parent).map_err(|error| OciError::CreateParent {
            path: parent.to_owned(),
            message: error.to_string(),
        })?;
    }
    let temp = fresh_temp_dir(dest)?;
    let outcome =
        write_layout(&temp, bundle, &exported, &config, &manifest, &index).and_then(|()| {
            fs::rename(&temp, dest).map_err(|error| OciError::Publish {
                temp: temp.clone(),
                dest: dest.to_owned(),
                message: error.to_string(),
            })
        });
    if outcome.is_err() {
        let _ = fs::remove_dir_all(&temp);
    }
    outcome?;
    verify_layout(dest, bundle, &exported, &config, &manifest, &index)?;
    Ok(exported)
}

/// Writes the five layout files into the temporary directory.
fn write_layout(
    temp: &Path,
    bundle: &[u8],
    exported: &ExportedLayout,
    config: &str,
    manifest: &str,
    index: &str,
) -> Result<(), OciError> {
    let blobs = temp.join("blobs/sha256");
    fs::create_dir_all(&blobs).map_err(|error| OciError::WriteFile {
        path: blobs.clone(),
        message: error.to_string(),
    })?;
    for (relative, bytes) in [
        ("oci-layout".to_owned(), render_oci_layout().into_bytes()),
        ("index.json".to_owned(), index.as_bytes().to_vec()),
        (
            format!("blobs/sha256/{}", format_digest(exported.manifest)),
            manifest.as_bytes().to_vec(),
        ),
        (
            format!("blobs/sha256/{}", format_digest(exported.config)),
            config.as_bytes().to_vec(),
        ),
        (
            format!("blobs/sha256/{}", format_digest(exported.layer)),
            bundle.to_vec(),
        ),
    ] {
        let path = temp.join(relative);
        fs::write(&path, bytes).map_err(|error| OciError::WriteFile {
            path,
            message: error.to_string(),
        })?;
    }
    Ok(())
}

/// Re-reads the finished layout in two steps: every file must match the
/// generated bytes, and every digest-addressed file must hash to the digest
/// its file name claims. Descriptor-to-blob cross-checks need JSON parsing
/// and arrive with the #17 reader.
fn verify_layout(
    dest: &Path,
    bundle: &[u8],
    exported: &ExportedLayout,
    config: &str,
    manifest: &str,
    index: &str,
) -> Result<(), OciError> {
    let files = [
        ("oci-layout".to_owned(), render_oci_layout().into_bytes()),
        ("index.json".to_owned(), index.as_bytes().to_vec()),
        (
            format!("blobs/sha256/{}", format_digest(exported.manifest)),
            manifest.as_bytes().to_vec(),
        ),
        (
            format!("blobs/sha256/{}", format_digest(exported.config)),
            config.as_bytes().to_vec(),
        ),
        (
            format!("blobs/sha256/{}", format_digest(exported.layer)),
            bundle.to_vec(),
        ),
    ];
    for (relative, expected) in &files {
        let actual = fs::read(dest.join(relative)).map_err(|_| OciError::Readback {
            message: format!("{relative} cannot be read back"),
        })?;
        if actual != *expected {
            return Err(OciError::Readback {
                message: format!("{relative} differs from the generated bytes"),
            });
        }
    }
    for (relative, digest) in [
        ("index.json".to_owned(), exported.index),
        (
            format!("blobs/sha256/{}", format_digest(exported.manifest)),
            exported.manifest,
        ),
        (
            format!("blobs/sha256/{}", format_digest(exported.config)),
            exported.config,
        ),
        (
            format!("blobs/sha256/{}", format_digest(exported.layer)),
            exported.layer,
        ),
    ] {
        let actual = fs::read(dest.join(&relative)).map_err(|_| OciError::Readback {
            message: format!("{relative} cannot be read back"),
        })?;
        if digest_of(&actual) != digest {
            return Err(OciError::Readback {
                message: format!("{relative} does not hash to its descriptor digest"),
            });
        }
    }
    Ok(())
}

/// Creates a fresh sibling temporary directory for one export.
fn fresh_temp_dir(dest: &Path) -> Result<PathBuf, OciError> {
    static NEXT_TEMP_ID: AtomicU64 = AtomicU64::new(0);
    let file_name = dest
        .file_name()
        .map(|name| name.to_string_lossy().into_owned())
        .unwrap_or_else(|| "layout".to_owned());
    for _ in 0..128 {
        let id = NEXT_TEMP_ID.fetch_add(1, Ordering::Relaxed);
        let temp = dest.with_file_name(format!(".{file_name}.tmp.{}-{id}", std::process::id()));
        if fs::symlink_metadata(&temp).is_ok() {
            continue;
        }
        match fs::create_dir(&temp) {
            Ok(()) => return Ok(temp),
            Err(error) if error.kind() == std::io::ErrorKind::AlreadyExists => continue,
            Err(error) => {
                return Err(OciError::CreateTemp {
                    path: temp,
                    message: error.to_string(),
                });
            }
        }
    }
    Err(OciError::CreateTemp {
        path: dest.to_owned(),
        message: "temporary directory names are exhausted".to_owned(),
    })
}

/// SHA-256 digest of one byte string.
fn digest_of(bytes: &[u8]) -> [u8; 32] {
    let mut hasher = Sha256::new();
    hasher.update(bytes);
    hasher.finalize().into()
}

#[cfg(test)]
mod tests {
    use super::*;
    use minicontainer_bundle::ImageSpec;

    const LAYER_DIGEST: &str = "5b5bfa03d58cf705f1e4b2b25c7deff040dacd6d07c9530bb413af759873b07d";
    const CONFIG_DIGEST: &str = "883d7fa4996b5ab067214dd9b4d64a83805f61bbef9ff30912067d88e9247835";
    const MANIFEST_DIGEST: &str =
        "64287f614ec08171127db4f9e411767d2ea1d635b9ec560377e0cdbed7367eeb";
    const INDEX_DIGEST: &str = "f1eaff19e582d40560022d45a8819cfd28a657bd9f88c318008ef46f1759634c";

    /// The golden fixture from the mapping reference: name `hello`, no
    /// arguments, ELF bytes `0x00` through `0x0f`.
    fn golden_bundle() -> Vec<u8> {
        let elf: Vec<u8> = (0..16).collect();
        minicontainer_bundle::build(ImageSpec {
            name: "hello",
            args: &[],
            elf: &elf,
        })
        .expect("golden bundle builds")
    }

    #[test]
    fn export_matches_the_golden_layout_bytes() {
        let root = fixture_root();
        let dest = root.join("layout");
        let bundle = golden_bundle();
        assert_eq!(bundle.len(), 136);

        let exported = export_bundle(&bundle, &dest).expect("export");
        assert_eq!(format_digest(exported.layer), LAYER_DIGEST);
        assert_eq!(format_digest(exported.config), CONFIG_DIGEST);
        assert_eq!(format_digest(exported.manifest), MANIFEST_DIGEST);
        assert_eq!(format_digest(exported.index), INDEX_DIGEST);

        assert_eq!(
            fs::read(dest.join("oci-layout")).expect("oci-layout"),
            b"{\"imageLayoutVersion\":\"1.0.0\"}"
        );
        let index = fs::read(dest.join("index.json")).expect("index");
        assert_eq!(index.len(), 292);
        assert_eq!(format_digest(digest_of(&index)), INDEX_DIGEST);
        let manifest =
            fs::read(dest.join(format!("blobs/sha256/{MANIFEST_DIGEST}"))).expect("manifest");
        assert_eq!(manifest.len(), 411);
        let config = fs::read(dest.join(format!("blobs/sha256/{CONFIG_DIGEST}"))).expect("config");
        assert_eq!(config.len(), 197);
        let layer = fs::read(dest.join(format!("blobs/sha256/{LAYER_DIGEST}"))).expect("layer");
        assert_eq!(layer, bundle, "the layer blob is the MiniBundle file");

        let again = export_bundle(&bundle, &root.join("again")).expect("second export");
        assert_eq!(exported, again, "export must be deterministic");
        fs::remove_dir_all(&root).expect("cleanup");
    }

    #[test]
    fn export_rejects_invalid_bundles_and_existing_destinations() {
        let root = fixture_root();
        let bundle = golden_bundle();

        let mut corrupted = bundle.clone();
        corrupted[100] ^= 1;
        assert!(matches!(
            export_bundle(&corrupted, &root.join("bad")),
            Err(OciError::Bundle(_))
        ));
        assert!(!root.join("bad").exists(), "no partial layout may remain");

        let dest = root.join("layout");
        export_bundle(&bundle, &dest).expect("first export");
        assert_eq!(
            export_bundle(&bundle, &dest),
            Err(OciError::DestinationExists { path: dest.clone() })
        );
        let file = root.join("file");
        fs::write(&file, b"x").expect("file");
        assert_eq!(
            export_bundle(&bundle, &file),
            Err(OciError::DestinationExists { path: file.clone() })
        );
        fs::remove_dir_all(&root).expect("cleanup");
    }

    #[test]
    fn export_leaves_no_temporary_directories_behind() {
        let root = fixture_root();
        let dest = root.join("nested/deep/layout");
        export_bundle(&golden_bundle(), &dest).expect("export creates parents");
        let mut leftovers = Vec::new();
        for entry in fs::read_dir(root.join("nested/deep")).expect("list") {
            let name = entry.expect("entry").file_name();
            if name.to_string_lossy().contains(".tmp.") {
                leftovers.push(name);
            }
        }
        assert!(leftovers.is_empty(), "temporary dirs remain: {leftovers:?}");
        assert!(dest.join("index.json").exists());
        fs::remove_dir_all(&root).expect("cleanup");
    }

    #[test]
    fn readback_detects_a_corrupted_layer_blob() {
        let root = fixture_root();
        let dest = root.join("layout");
        let bundle = golden_bundle();
        let exported = export_bundle(&bundle, &dest).expect("export");
        let layer_path = dest.join(format!("blobs/sha256/{LAYER_DIGEST}"));
        let mut layer = fs::read(&layer_path).expect("layer");
        layer[0] ^= 1;
        fs::write(&layer_path, layer).expect("corrupt");
        let config = render_config("hello", &[], LAYER_DIGEST);
        let manifest = render_manifest(CONFIG_DIGEST, 197, LAYER_DIGEST, 136);
        let index = render_index(MANIFEST_DIGEST, 411);
        assert!(matches!(
            verify_layout(&dest, &bundle, &exported, &config, &manifest, &index),
            Err(OciError::Readback { .. })
        ));
        fs::remove_dir_all(&root).expect("cleanup");
    }

    fn fixture_root() -> PathBuf {
        static NEXT_FIXTURE_ID: AtomicU64 = AtomicU64::new(0);
        let id = NEXT_FIXTURE_ID.fetch_add(1, Ordering::Relaxed);
        std::env::temp_dir().join(format!("minicontainer-oci-{}-{id}", std::process::id()))
    }
}
